### ISSUE TITLE
npm run build 報錯

### ISSUE THREAD

**Issue by wangchenyi1996** [BiYuqi/vue-multiple-pages#2]
vue.config.js 文件注釋這幾行代碼就正常了      
// config.plugin('extract-css').use(MiniCssExtractPlugin, [
      //   {
      //     filename: bundle => {
      //       return bundle.chunk.name === 'index' ? 'css/[name].[contenthash:8].css' : '[name]/[name].[contenthash:8].css'
      //     },
      //     chunkFilename: 'css/[name].[contenthash:8].css'
      //   }
      // ])

**Comment by BiYuqi** [comment]
@wangchenyi1996 [按页面输出的分支确实有问题](https://github.com/BiYuqi/vue-multiple-pages/tree/support-build-nest-folder) 感谢提醒，我也试了升级，包括升级mini的版本，目前还是有问题，我先注释了，估计是file-loader的版本有冲突。再排查下
